### ISSUE TITLE
question about nethunter

### ISSUE THREAD

**Issue by hxrofo** [derv82/wifite2#151]
hello guys
does wifite2 work on kali nethunter? i have nexus 5, and the old wifite works fine with the internal wifi card using monstart-nh...but i'm wondering if someone managed to make the new version of wifite work too. thanks

**Comment by More2Chi** [comment]
I was able to run Wifite2 on my Nexus 5x Nethunter perfectly, using a external wifi adapter.
Also, I didn't install Wifite2 as i thought it might interfere with the stock wifite included in NH. So i just ran it as a script.

Here's what I did.

git clone https://github.com/derv82/wifite2.git
cd wifite2
sudo ./Wifite.py (plus any flags - IE --mac, --pmkid)

Lastly, in order to run PMKID attacks, I needed to add an alias for hashcat, as its not able to run on our phones.
