### ISSUE TITLE
Run PMKID Attack without hashcat crack 

### ISSUE THREAD

**Issue by More2Chi** [derv82/wifite2#173]
how do I run a PMKID Attack without hashcat? example usage: run PMKID Attack on Nethunter with wifite/wifite 2 and save file instead of cracking.. i tried running (sudo priv) wifite.py -mac --pmkid to force with the same result (skips attack cause hashcat is "missing")

FYI - i read the other posts and they didn't answer what to actually do or fix

**Comment by RaduNico** [comment]
Hello!

This change is not currently in the Wifite master branch, however PR #159 comes to fix this.

A workaround suggested in #149 is doing `alias hashcat=/bin/false`. Anything that makes `hashcat` a valid command to run from the terminal will probably work.

**Comment by More2Chi** [comment]
So i tried entering " alias hashcat=/bin/false " into the terminal then running wifite, But its still skipping PMKID because hashcat is missing. 

Any tips?

**Comment by RaduNico** [comment]
Try adding the following lines to your `~/.bashrc` file:

```
alias sudo='sudo '
alias hashcat='/bin/false'
```
You can add those lines anywhere, preferably to the end of the file. Just make sure you do not add them inside an if. After you do this you need to open a new shell to 'refresh' the settings. If you ever install hashcat don't forget to remove those lines!

If this does not work then create a small script using your favorite text editor in /sbin/hashcat that contains:
```
#!/bin/bash

/bin/false
```

Don't forget to run 'chmod +x /sbin/hashcat'. Because sbin is owned by root you will need to do the above commands using sudo.

**Comment by More2Chi** [comment]
Thanks! I got it working via the 2nd method, Added hashcat containing the bash script to /sbin/ and made it executable.
