### ISSUE TITLE
WPS networks not displaying as WPS networks

### ISSUE THREAD

**Issue by sugafree** [derv82/wifite2#73]
Hi,

Seems like I have to reopen this issue. I am using the new R87 wifite and wash 1.6.4.

When scanning for targets, all APs says no WPS even though I know most of them has (including mine to play with) as well as wash returns different results. When running wifite with --wps, it does return a few targets, but as soon as one appears, it will disappear in 1 sec, so it will have no targets to attack..

Any idea?

**Comment by derv82** [comment]
Wifite R87 is the old wifite: https://github.com/derv82/wifite

This is repo is for Wifite2: https://github.com/derv82/wifite2 a rewrite of Wifite R87 (confusingly also called "2").

Wash made some changes recently which broke WPS detection for .cap files in Wifite (both the old one and the newer version on this repo).

See #62 where this was reported & fixed in Wifite2. It's probably still a bug in the old Wifite R87.

I'm focusing on making Wifite2, and am ignoring the old wifite, hoping to replace it in Kali/etc once Wifite2 is ready for public release.
