### ISSUE TITLE
Feature request: Make tshark optional again for compatibility

### ISSUE THREAD

**Issue by Niller303** [derv82/wifite2#77]
Small systems running OpenWRT and others don't have access to tshark, but they can use tcpdump.
So i would request that using tcpdump, and wash instead became an option.

**Comment by derv82** [comment]
Whoops. I keep forgetting people aren't running Kali. But if Wifite2 is to replace the old Wifite, I'll need to support as many setups as possible.

I don't know if/how `tcpdump` could detect WPS networks. But Wash certainly can (at least the latest versions -- see #62 which led to using `tshark` instead of `wash`).
